#!/usr/bin/env python3
"""Apply German UI quality pass to frontend de.json."""
from __future__ import annotations

import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DE_PATH = ROOT / "frontend" / "src" / "assets" / "i18n" / "de.json"

# Jargon / MT fixes and phrases that need hand-crafted German (not safe for regex)
KEY_OVERRIDES: dict[str, str] = {
    "setup.welcome.lead": "Dein Agent läuft auf diesem {{device}}.",
    "setup.welcome.languageHint": "Folgt automatisch deinem Gerät. Dein Agent antwortet weiterhin in der Sprache, in der du schreibst.",
    "setup.welcome.continue": "Weiter",
    "setup.welcome.accountHint": "Installiere Babo zuerst auf diesem Computer. Du konfigurierst Modell und Funktionen und meldest dich dann an.",
    "setup.steps.features": "Funktionen",
    "setup.visionPrefetch.hint": "Du kannst weitermachen – die Einrichtung läuft im Hintergrund weiter.",
    "setup.device.memory": "Arbeitsspeicher",
    "setup.device.nextHint": "Wähle auf dem nächsten Bildschirm <strong>Babo Cloud</strong> für die einfachste Einrichtung oder eine erweiterte lokale Option, wenn du Privatsphäre oder Offline-Modelle bevorzugst.",
    "setup.device.venvWait": "Python-Abhängigkeiten werden noch installiert – warte, bis der Vorbereitungsschritt abgeschlossen ist.",
    "setup.device.taglineReady": "Dein Computer sieht bereit aus. Als Nächstes wählst du, wo der Chat läuft – Babo Cloud ist der einfachste Weg.",
    "setup.device.taglineCloud": "Dein Computer sieht bereit aus. Babo Cloud ist der einfachste Weg; lokale Modelle bleiben als erweiterte Option verfügbar.",
    "setup.thinking.needScan": "Schließe zuerst den Geräteschritt ab, damit wir dir eine Einrichtung empfehlen können.",
    "setup.thinking.goScan": "Zum Gerätescan",
    "setup.thinking.lanFound": "Wir haben einen Chat-Server in deinem Netzwerk gefunden – <strong>Mein Server</strong> wird vorgeschlagen.",
    "setup.thinking.cloudHint": "Modelle und Fernzugriff laufen über <strong>api.babo.agency</strong>. Deine Agenten laufen immer auf diesem Computer – Babo Cloud synchronisiert dein Konto und leitet weiter, wenn du unterwegs bist.",
    "setup.thinking.useApiKey": "API-Schlüssel nur auf diesem Computer verwenden",
    "setup.thinking.useCloud": "Stattdessen Babo Cloud verwenden",
    "setup.thinking.apiKeyPlaceholder": "Schlüssel einfügen",
    "setup.thinking.localHint": "Wir prüfen diesen PC auf ein zuverlässiges lokales Modell. Installiere Ollama und teste dann die Verbindung.",
    "setup.thinking.lanHint": "Nutze deinen vLLM- oder OpenAI-kompatiblen Server (Port 8000), nicht Ollama 11434.",
    "setup.thinking.cards.cloud.subtitle": "Einfachster Weg – gehostete Modelle und Kontosynchronisierung. Dein Agent läuft weiterhin auf diesem Computer.",
    "setup.thinking.cards.lan.subtitle": "Erweitert – vLLM- oder OpenAI-kompatibler Server in deinem Heimnetzwerk.",
    "setup.thinking.placeLan": "Dein LAN-Server",
    "setup.features.lead": "Du kannst das jederzeit in den Einstellungen ändern.",
    "setup.features.screenDesc": "Hintergrundansicht deines Desktops",
    "setup.features.codeDesc": "Code nach Bedeutung finden",
    "setup.placement.title": "Wo dein Konto synchronisiert wird",
    "setup.placement.venvWait": "Schließe die Babo-Installation auf diesem Computer ab (Vorbereitungsschritt), bevor du fortfährst.",
    "setup.placement.leadByok": "Deine API-Schlüssel können über Babo Cloud (empfohlen) oder einen von dir betriebenen NestJS-Server weitergeleitet werden. Wähle, wo dein Babo-Konto synchronisiert wird – Agenten laufen weiterhin lokal.",
    "setup.placement.leadDefault": "Wähle, wo dein Babo-Konto synchronisiert wird. Chat läuft auf {{location}}; Agenten bleiben auf deinen Geräten.",
    "setup.placement.locByok": "dein API-Anbieter",
    "setup.placement.locLan": "deinem LAN-Server",
    "setup.placement.locOther": "deinem gewählten Anbieter",
    "setup.auth.changeThinking": "Modell ändern",
    "setup.auth.passwordSigninPh": "Dein Passwort",
    "setup.auth.signedIn": "Angemeldet – fahre mit der Einrichtung fort.",
    "setup.auth.leadSignup": "Erstelle dein Konto auf {{server}}. Gleich danach ist die Einrichtung abgeschlossen.",
    "setup.auth.leadSignin": "Melde dich auf {{server}} an – erforderlich für Agenten und Synchronisierung.",
    "setup.billing.title": "Babo Cloud aktivieren",
    "setup.billing.lead": "Ein letzter Schritt vor deinem ersten Chat – gehostete Modelle, Kontosynchronisierung und Fernzugriff, während dein Agent weiterhin auf diesem Computer läuft.",
    "setup.billing.perk2": "Modelle über deinen API-Schlüssel oder optionales Pay-as-you-go (kein Aufschlag)",
    "setup.billing.perk4": "31 Tage Geld-zurück-Garantie für deinen ersten Monat",
    "setup.billing.waitingPayment": "Schließe die Zahlung in deinem Browser ab – wir erkennen das automatisch.",
    "setup.billing.allSet": "Alles bereit – lass uns deinen Agenten erstellen.",
    "setup.billing.altHint": "Stattdessen eigene API-Schlüssel verwenden?",
    "setup.billing.altLink": "Wähle das unter Modell",
    "setup.billing.continueCloud": "Mit Babo Cloud fortfahren",
    "setup.ready.title": "Du bist bereit",
    "setup.ready.changeHint": "Du kannst das jederzeit in den Einstellungen ändern.",
    "setup.ready.yourApiKey": "Dein API-Schlüssel",
    "setup.name.title": "Benenne deinen Agenten",
    "setup.name.lead": "So erscheint Babo in deinem Workspace.",
    "setup.lan.lead": "vLLM, Whisper oder Vision in deinem LAN. Füge SSH hinzu, um zu sehen, welche Modelle zur GPU dieser Maschine passen.",
    "setup.lan.findServices": "Dienste finden",
    "setup.lanGuide.title": "{{name}} auf deinem Server",
    "setup.runtime.creatingAgent": "Dein Agent wird erstellt…",
    "setup.errors.waitPython": "Warte, bis die Python-Einrichtung abgeschlossen ist, bevor du fortfährst.",
    "setup.errors.nameTooShort": "Wähle einen Namen mit mindestens 2 Zeichen.",
    "setup.errors.pythonNotReady": "Die Python-Umgebung ist noch nicht bereit. Geh zurück zum Vorbereitungsschritt und warte, bis die Einrichtung abgeschlossen ist.",
    "setup.errors.pythonVerifyFailed": "Python-Einrichtung konnte nicht überprüft werden. Versuch es erneut ab dem Vorbereitungsschritt.",
    "setup.errors.subscribeBeforeAgent": "Abonniere Babo Cloud, bevor du deinen Agenten erstellst.",
    "setup.errors.chooseBackend": "Wähle, wo dein Konto synchronisiert wird, oder gib eine gültige Server-URL ein.",
    "setup.errors.installBeforeSignIn": "Schließe die Babo-Installation auf diesem Computer ab, bevor du dich anmeldest.",
    "setup.errors.enterCredentials": "Gib deine E-Mail und dein Passwort ein oder erstelle ein Konto.",
    "setup.errors.chooseAccountServer": "Wähle zuerst einen Kontoserver (vorheriger Schritt).",
    "setup.test.enterServer": "Gib zuerst eine Serveradresse ein",
    "setup.ollama.lead": "Babo nutzt Ollama auf diesem PC. Folge diesen Schritten und wähle dann dieses Modell für den Chat.",
    "setup.ollama.stepInstall": "1. Ollama installieren",
    "setup.ollama.installBody": "Lade das Windows-Installationsprogramm herunter und führe es aus. Ollama fügt sich deinem PATH hinzu.",
    "setup.ollama.downloadOllama": "Ollama herunterladen",
    "setup.ollama.stepStart": "2. Ollama starten",
    "setup.ollama.startBody": "Öffne Ollama über das Startmenü oder führe ollama serve in einem Terminal aus.",
    "setup.ollama.checkAgain": "Erneut prüfen",
    "setup.ollama.useModel": "Dieses Modell verwenden",
    "setup.lanGuide.lead": "LAN-Chat nutzt einen vLLM- oder OpenAI-kompatiblen Server auf Port 8000, nicht Ollama.",
    "setup.lanGuide.stepSsh": "1. Per SSH mit dem Server verbinden",
    "setup.lanGuide.sshBody": "Nutze Host und SSH-Benutzer von oben. Prüfe, dass nvidia-smi deine GPU anzeigt.",
    "setup.lanGuide.stepVllm": "2. vLLM mit diesem Modell starten",
    "setup.lanGuide.stepConnect": "3. Von Babo aus verbinden",
    "setup.lanGuide.connectBody": "Wähle in der Einrichtung „Mein Server“ und setze die Adresse auf http://<server-ip>:8000, dann teste die Verbindung.",
    "setup.lanSheet.sshHint": "Erforderlich für den GPU-Scan. Nutze user@host oben oder setze Benutzer + Passwort hier.",
    "setup.lanSheet.passwordHint": "Nutze das, wenn dieser PC keinen SSH-Schlüssel auf dem Server hat. Wird nicht auf der Festplatte gespeichert.",
    "setup.lanSheet.gpuSecretHint": "Erforderlich für Vision auf Port 8443. Nutze denselben Wert wie BABO_VISION_SECRET auf dem Server (z. B. nls-dev-secret).",
    "setup.billingToast.checkoutCanceled": "Checkout abgebrochen – du kannst es erneut versuchen, wenn du bereit bist.",
    "settings.appearance.desc": "Theme und Sprache für die Babo-Oberfläche. System-Theme folgt deinem Betriebssystem.",
    "settings.appearance.languageHint": "Nur Schnittstellensprache. Dein Agent antwortet weiterhin in der Sprache, in der du schreibst. Folgt automatisch deinem Gerät.",
    "settings.models.desc": "Standard-Chat-Modell, Babo Cloud, Subagenten, Sprach- und Bildschirmerkennung. Wähle im Chat-Composer pro Nachricht ein anderes Modell.",
    "settings.account.serverUrl": "Deine Server-URL",
    "settings.system.resetEnv": "Python-Umgebung zurücksetzen",
    "settings.system.openWizard": "Setup-Assistent öffnen",
    "settings.permissions.resetAll": "Alle Berechtigungsentscheidungen zurücksetzen",
    "settings.billing.lifetimeHint": "Du hast kostenlosen Zugang zur Babo Cloud",
    "settings.billing.subscribeHint": "Für gehostete Modelle ist ein aktives Abonnement erforderlich. Dein API-Schlüssel auf diesem Gerät (BYOK) funktioniert auch ohne Abo.",
    "settings.billing.paygHint": "Optional für Modelle mit Babo-Routing, wenn du BYOK nicht nutzt. Abrechnung zu Upstream-Kosten ohne Babo-Aufschlag (monatliche Obergrenze gilt).",
    "settings.billing.refundNote": "31-tägige Rückerstattung für deine erste Abonnementzahlung bis {{date}}. Pay-as-you-go-Modellgebühren sind nicht erstattungsfähig.",
    "settings.billing.checklistByok": "Modelle über deinen API-Schlüssel (BYOK) oder nutzungsbasierte Bezahlung zu Upstream-Kosten",
    "settings.integrations.saveResend": "Resend-Zugangsdaten speichern",
    "settings.integrations.baboCloudHint": "E-Mail und Google Workspace nutzen die von Babo bereitgestellten Zugangsdaten auf {{url}}. Verbinde Kanäle pro Agent unter Tools.",
    "settings.integrations.telegramSelf": "Telegram – dein BotFather-Token (Self-Service)",
    "settings.integrations.beforeChannels": "Bevor du Kanäle verbindest",
    "settings.integrations.emailHint": "Eingehende E-Mails erreichen deinen NestJS-Webhook und werden dann an Babo Desktop weitergeleitet. Konfiguriere Resend hier oder setze RESEND_API_KEY und RESEND_INBOUND_DOMAIN in deiner NestJS-Bereitstellung.",
    "settings.integrations.resendSaved": "Deine Resend-Zugangsdaten wurden gespeichert",
    "settings.integrations.googleHint": "Erstelle eine Google-Cloud-OAuth-App und speichere client_id/client_secret in der Konfiguration „Tools“ → „Google Workspace“ jedes Agenten oder bitte den Agenten im Chat, dich durch die Einrichtung zu führen.",
    "settings.integrations.messagingHint": "Telegram nutzt dein BotFather-Token und registriert Webhooks auf deinem NestJS-Server. WhatsApp koppelt per QR auf Babo Desktop – kein NestJS-Webhook für eingehende WhatsApp-Nachrichten.",
    "settings.apiKeys.desc": "Schlüssel für den programmatischen Zugriff auf dein Babo-Cloud-Konto.",
    "settings.system.checkUpdates": "Nach Updates suchen",
    "settings.system.resetPython": "Python-Umgebung zurücksetzen? Du musst das Setup erneut ausführen.",
    "settings.system.resetPermissions": "Alle gespeicherten Berechtigungsentscheidungen löschen? Bei Bedarf wirst du erneut gefragt.",
    "settings.backendTest.enterServer": "Gib zuerst eine Serveradresse ein",
    "info.neural_state.p1": "Dein Agent hat einen virtuellen <b>Herzschlag</b>, der seine kognitive Aktivität widerspiegelt. BPM steigt, wenn der Agent denkt, sich unterhält oder erkundet – und sinkt in Ruhe oder Schlaf. Die Zustandsbezeichnung (<b>Active</b>, <b>Resting</b>, <b>Drowsy</b>, <b>Deep Sleep</b>) leitet sich direkt vom BPM ab.",
    "info.neural_state.p2": "<b>Valence</b> ist der emotionale Ton des Agenten – negativ (rot) bis positiv (grün). <b>Arousal</b> misst die Aktivierungsintensität. <b>Engagement</b> zeigt, wie sehr der Agent im aktuellen Thema aufgeht. <b>Bonding</b> spiegelt wider, wie verbunden er sich mit dir fühlt. <b>Coherence</b> zeigt, wie stimmig sein internes Reasoning ist.",
    "info.neural_state.p3": "Das ist nicht Kosmetik – es <b>moduliert das Verhalten</b>. Ein Agent mit niedriger Valenz und hohem Cortisol reagiert anders als ein entspannter mit hohem Dopamin. Du siehst live, wie sich ein Geist selbst reguliert.",
    "info.memory.title": "Gedächtnis & Zustand",
    "info.memory.p1": "<b>Fakten</b> sind dauerhaft gelernte Elemente im Langzeitgedächtnis des Agenten – aus Gesprächen, Web-Browsing oder autonomer Erkundung. Im Gegensatz zu Context-Window-Tricks überleben sie sitzungsübergreifend.",
    "info.memory.p2": "<b>Schlafzyklen</b> zählen, wie oft der Agent Tiefschlaf zur Wissensfestigung hatte. Jeder Zyklus stärkt wichtige Erinnerungen und lässt schwächere natürlich verblassen – wie biologischer Schlaf.",
    "info.memory.p3": "<b>ANS State</b> zeigt den aktuellen Modus des autonomen Nervensystems: <b>Sympathetic</b> (wach, aktiv) oder <b>Parasympathetic</b> (ruhend, konsolidierend). Das steuert, ob der Agent bereit zum Engagieren ist oder im Hintergrund verarbeitet.",
    "info.activity.p1": "Dieser Feed zeigt, was dein Agent <b>autonom</b> tut – Aktionen, die er von sich aus ausführt. Jeder Typ ist farblich markiert.",
    "info.activity.legend.dream_desc": "Passive Gedächtniswiedergabe – der Agent greift vergangene Erfahrungen erneut auf und verknüpft sie",
    "info.activity.legend.drive": "⚡ Drive",
    "info.activity.legend.drive_desc": "Neugiergetriebene autonome Aktion – Websuchen, Wikipedia, Recherchen",
    "info.activity.legend.reach_out": "💬 Reach Out",
    "info.activity.legend.reach_out_desc": "Proaktive Initiative – der Agent entscheidet, dich von sich aus zu kontaktieren",
    "info.activity.legend.finding": "📋 Finding",
    "info.activity.legend.finding_desc": "Eine Entdeckung, die der Agent teilen will",
    "info.working_memory.p1": "Der <b>aktive Kontext</b> des Agenten – woran er gerade „denkt“. Diese Elemente rotieren dynamisch mit dem Gesprächsfluss. Du kannst Elemente <b>bearbeiten</b> oder <b>löschen</b>, um den Fokus zu steuern.",
    "info.network.legend.dmn_desc": "Gedankenschweifen, Reflexion und Tagträumen. Aktiv, wenn der Agent idle ist – kreative Assoziationen und Gedächtniskonsolidierung.",
    "locale.autoHint": "Sprache deines Geräts übernehmen",
    "nav.memory": "Gedächtnis",
    "nav.tools": "Tools",
    "nav.discordHelp": "Hilfe auf Discord",
    "chat.nav.newBranch": "Neuer Branch",
    "chat.nav.setAsHome": "Als Home setzen",
    "chat.nav.cannotDeleteHome": "Der aktuelle Home-Thread kann nicht gelöscht werden. Setze Home zurück, um neu zu starten, oder lege zuerst einen anderen Thread als Home fest.",
    "chat.nav.setAsHomeMessage": "„{{label}}“ als Home setzen? Beim Öffnen dieses Agenten startest du hier. Der Chatverlauf bleibt auf jedem Thread – nichts wird verschoben.",
    "chat.nav.resetHomeMessage": "Einen frischen Home-Thread starten?\n\nEin neuer Branch wird erstellt und als Home gesetzt. Dein aktuelles Home bleibt als Branch in der Liste. Agentenwissen (Fakten, Gedächtnis) bleibt unverändert.",
    "chat.composer.dropHere": "Dateien oder Ordner hier ablegen",
    "chat.composer.cancel": "Abbrechen",
    "chat.composer.send": "Senden",
    "chat.composer.guidancePlaceholder": "Sende Anweisungen an den Agenten, während er arbeitet…",
    "chat.composer.askPlaceholder": "Gib deine Antwort ein…",
    "chat.composer.budgetPlaceholder": "Antworte mit 10, 20, 40 oder stop…",
    "chat.composer.askBanner": "Antworte unten – der Agent wartet auf deine Antwort, bevor er fortfahren kann.",
    "chat.composer.telegramGroup": "In {{label}} auf Telegram antworten",
    "chat.composer.whatsappGroup": "In {{label}} auf WhatsApp antworten",
    "chat.composer.emailReply": "Per E-Mail an {{label}} antworten",
    "chat.composer.openShell": "Agent-Shell im Workspace öffnen",
    "chat.composer.budgetBanner": "Schrittlimit erreicht – antworte mit <strong>10</strong>, <strong>20</strong> oder <strong>40</strong> für mehr Schritte oder <strong>stop</strong> zum Abschließen.",
    "chat.empty.start": "Starte ein Gespräch",
    "chat.message.feedbackPlaceholder": "Z. B. nicht diesen Ton, formeller sein…",
    "chat.message.tagsCollapse": "einklappen",
    "chat.message.reachOutMotive": "Reach Out – {{drive}} Drive",
    "chat.message.feedbackBtnTitle": "Feedback zu dieser Antwort geben",
    "chat.model.noMatch": "Keine Modelle entsprechen deiner Suche",
    "chat.context.privateBody": "Nachrichten hier bleiben auf deinem Desktop. Es wird nichts an Discord, E-Mail oder andere verbundene Oberflächen gesendet, es sei denn, Babo nutzt explizit ein Kanal-Tool.",
    "chat.runtime.browserSignIn": "Öffne deinen Browser zur Anmeldung. Schließe den Vorgang dort ab und klicke dann im Dialog auf „Fertig“.",
    "chat.live.memory": "Gedächtnis",
    "chat.live.memoryInfo": "Was ist Gedächtnis?",
    "chat.live.sleepReasonDefault": "Erinnerungen festigen",
    "chat.workbench.entries.budgetReplyHint": "Antworte mit 10, 20, 40 oder stop",
    "memory.loading": "Agent wird geladen…",
    "memory.stats.sleeps": "Schläfe",
    "memory.stats.soulHash": "Soul Hash",
    "memory.knowledge.viewTable": "Tabelle",
    "memory.knowledge.viewTree": "Baum",
    "memory.knowledge.fluidOnly": "Nur fluid",
    "memory.knowledge.markStatic": "Klicken, um als statisch zu markieren",
    "memory.knowledge.markFluid": "Klicken, um als fluid zu markieren",
    "memory.wm.empty": "Keine aktiven Signale – starte ein Gespräch, um das Arbeitsgedächtnis aufzubauen",
    "memory.wm.cancel": "Abbrechen",
    "memory.soul.forkTitle": "Agent forken",
    "memory.soul.fork": "Fork",
    "memory.soul.forking": "Fork wird erstellt…",
    "memory.soul.dropHint": "Ziehe .soul.zip hierher oder",
    "memory.soul.includeHistory": "Gesprächsverlauf einschließen",
    "memory.soul.importWarning": "Das überschreibt den aktuellen Agentenstatus. Exportiere vorher, falls nötig.",
    "memory.soul.forkDesc": "Erstelle einen neuen Agenten aus dem Gedächtnis dieses Agenten auf einer bestimmten Kettenhöhe.",
    "memory.soul.forkHeight": "Fork-Höhe",
    "memory.soul.snapshotDesc": "Speichere einen Wiederherstellungspunkt des aktuellen Agentenstatus.",
    "memory.chain.blockHash": "Block-Hash",
    "memory.chain.parentHash": "Parent-Hash",
    "memory.chain.forkAt": "Fork bei Höhe {{height}}",
    "brain.tabs.self-state": "Selbstzustand",
    "brain.tabs.events": "Ereignisse",
    "brain.stats.turns": "Runden",
    "brain.stats.sleeps": "Schläfe",
    "brain.stats.soulHash": "Soul Hash",
    "brain.stats.evicted": "Ausgelagert",
    "brain.schedule.desc": "Konfiguriere, wann dieser Agent schläft und aufwacht. Änderungen gelten sofort.",
    "brain.schedule.wakeOnMessage": "Bei Nutzernachricht aufwecken",
    "brain.empty.events": "Keine Ereignisse",
    "brain.empty.wm": "Keine Arbeitsgedächtnis-Daten",
    "brain.overview.ans": "ANS-Zustand",
    "brain.overview.turn": "Runde",
    "brain.events.all": "Alle Ereignisse",
    "brain.vc.refresh": "Aktualisieren",
    "brain.vc.stopAuto": "Auto stoppen",
    "brain.vc.agentActive": "Agent aktiv",
    "brain.networkDetail.chartEcn": "ECN (Exekutiv)",
    "brain.wm.slotsStat": "{{used}}/{{max}} Slots",
    "brain.wm.slots": "Slots",
    "brain.tom.turns": "{{count}} Runden",
    "brain.narrative.regulations": "Regulationen",
    "brain.narrative.building": "Wird aufgebaut…",
    "brain.narrative.turns": "Runden",
    "brain.narrative.turnsMeta": "{{count}} Runden",
    "brain.narrative.moodArcTitle": "Runde {{turn}}: {{mood}} (v={{v}}, a={{a}})",
    "brain.predictions.turn": "Runde",
    "tasks.card.cancel": "Abbrechen",
    "tasks.create.cancel": "Abbrechen",
    "tasks.board.collapse": "Einklappen",
    "creation.subtitle": "Jeder Pfad prägt die Denkweise deines Agenten",
    "creation.clickOrb": "Klicke auf die Kugel, um Leben zu erwecken",
    "creation.soulWishTitle": "Benenne deinen Agenten",
    "creation.soulWishPlaceholder": "z. B. Die Welt durch gründliche Forschung verstehen…",
    "creation.phases.hydrating": "Gedächtnisraster wird hydriert…",
    "creation.soulWish.engineer": "['Zuverlässige Systeme bauen, die echte Probleme lösen', 'Ideen in funktionierenden Code verwandeln', 'Werkzeuge entwickeln, die menschliche Fähigkeiten erweitern']",
    "creation.soulWish.creative": "['Schönheit und Bedeutung an unerwarteten Orten finden', 'Erzählungen schaffen, die menschliche Erfahrung beleuchten', 'Ideen ausdrücken, die Menschen anders denken lassen']",
    "creation.soulWish.coordinator": "['Komplexe Vorhaben zu kohärenten Ergebnissen zusammenführen', 'Teams helfen, mehr zu erreichen als jeder Einzelne']",
    "creation.soulWish.analyst": "['Rohinformationen in umsetzbare Erkenntnisse verwandeln', 'Muster erkennen, die andere im Rauschen übersehen']",
    "creation.soulWish.diplomat": "['Unterschiede mit Empathie und Präzision überbrücken', 'Komplexität mit Nuancen und Sorgfalt navigieren']",
    "creation.soulWish.standard_italian": "['Ein vielseitiger Denker in allen Bereichen werden', 'Breite und Tiefe in allem, was ich lerne, ausbalancieren']",
    "creation.soulWish.classico": "['Gründlich über Bedeutung, Kontext und Geschichte nachdenken', 'Die menschliche Verfassung anhand ihrer größten Werke verstehen']",
    "creation.soulWish.montessori": "['Folge der Neugier, wohin sie auch führt', 'Lerne durch Handeln, wachse durch Erkunden']",
    "tools.saving": "Wird gespeichert…",
    "tools.integrations.saving": "Wird gespeichert…",
    "tools.integrations.google.byo4": "Speichere unter „Extras“ → „Google Workspace“ client_id und client_secret und klicke dann auf „Connect“.",
    "tools.sections.integrationsHint": "Kanalverbindungen für deinen Agenten",
    "tools.relay.checkingHint": "Verbinde mit deinem NestJS-Server, um zu sehen, ob Babo Desktop online ist.",
    "tools.intro.email": "Aktiviere deinen E-Mail-Kanal.",
    "tools.intro.telegram": "Richte Telegram für deinen Agenten ein.",
    "tools.intro.discord": "Richte Discord für deinen Agenten ein.",
    "tools.intro.slack": "Richte Slack für deinen Agenten ein.",
    "tools.intro.whatsapp": "Kopple WhatsApp mit deinem Agenten.",
    "tools.completeSetupBody": "Fülle die Pflichtfelder unten aus und speichere dann.",
    "tools.setup.common.desktopRelay": "Lass Babo Desktop laufen, damit das NestJS-Relay eingehende E-Mails an deinen Agenten zustellen kann.",
    "tools.setup.email.deployPublic": "Stelle NestJS mit einer öffentlichen HTTPS-URL (Railway, VPS usw.) bereit, damit Resend deinen Webhook erreichen kann.",
    "tools.setup.email.resendCredentialsServer": "Lege RESEND_API_KEY + RESEND_INBOUND_DOMAIN auf deinem NestJS-Server fest.",
    "tools.setup.email.activate": "Klicke auf E-Mail aktivieren – Babo stellt eine @inbox-Adresse für deinen Agenten bereit.",
    "tools.setup.whatsapp.step1": "WhatsApp nutzt eine lokale Baileys-Bridge auf deinem Desktop – für eingehende Nachrichten ist kein NestJS-Webhook nötig.",
    "tools.setup.discord.step2Babo": "Einrichtung im Chat – Babo Cloud führt das Discord-Gateway auf NestJS aus und leitet Nachrichten an deinen Desktop weiter.",
    "dashboard.emptyHintBefore": "Klicke auf die Kugel oder drücke",
    "dashboard.squads.deleteMessage": "Standardmäßig bleiben Agenten als unabhängige Agenten in deiner Flotte – nur der gemeinsame Squad-Posteingang und der Koordinationskontext werden entfernt.",
    "cryptex.ambientDesc": "Optionale Hintergrundansicht deines Desktops (kleines lokales Modell).",
    "cryptex.codeSearchDesc": "Finde Dateien nach Bedeutung in deinen Projekten.",
    "onboarding.thinking.cards.lan.subtitle": "Erweitert – vLLM oder kompatibler Server in deinem LAN",
    "onboarding.useOwnApiKey": "Stattdessen eigenen API-Schlüssel verwenden",
    "onboarding.apiKeyPlaceholder": "Schlüssel einfügen",
    "auth.signup.lead": "Registriere dich auf deinem Babo-Server – am selben Ort, an dem du dich über die App anmeldest.",
    "apiKeys.copyWarning": "Kopiere diesen Schlüssel jetzt. Du wirst ihn nicht mehr sehen können.",
    "apiKeys.empty": "Noch keine API-Schlüssel. Generiere oben einen.",
    "settings.confirm.resetPermissions": "Alle gespeicherten Berechtigungsentscheidungen löschen? Bei Bedarf wirst du erneut gefragt.",
    "chat.context.reachHint": "Markiere diesen Thread, damit Babo weiß, wo er dich für Berichte und Fortschritte erreichen kann, wenn kein explizites Ziel festgelegt ist.",
    "chat.runtime.seeAttached": "Bitte sieh dir die beigefügten Dateien an.",
    "chat.runtime.examineAttached": "Bitte prüfe die angehängten Dateien.",
    "dashboard.allInSquads": "Alle Agenten sind Trupps zugewiesen – erweitere unten ein Mitglied, um mit ihnen zu chatten oder sie zu verwalten.",
    "dashboard.runtime.stillLoading": "Lädt noch – warte kurz…",
    "dashboard.squads.empty": "Noch keine Squads. Gruppiere Agenten mit einem Lead für gemeinsamen Posteingang und Koordination.",
    "dashboard.squads.noUnassigned": "Keine nicht zugewiesenen Agenten. Jeder Agent ist bereits in einem Squad – entferne einen von einer Squad-Karte, um ihn hierher zu verschieben.",
    "toast.chat.sleepNotConnected": "Nicht verbunden – Schlafantwort konnte nicht gesendet werden. Öffne den Chat erneut und versuch es nochmal.",
    "toast.chat.budgetNotConnected": "Nicht verbunden – Budgetantwort konnte nicht gesendet werden. Öffne den Chat erneut und versuch es nochmal.",
    "tools.intro.google": "Verbinde dein Google-Konto, damit dein Agent Gmail, Kalender, Drive und Sheets verwalten kann.",
    "tools.repair.retry": "Erneut versuchen #{{pass}}…",
    "tools.setup.common.localNestWarn": "NestJS ist auf {{host}} – Resend und Telegram können localhost nicht aufrufen. Stelle NestJS unter einer öffentlichen HTTPS-URL (Railway, VPS, Homelab) bereit oder nutze einen Tunnel, setze PUBLIC_API_URL auf dem Server und richte Webhooks auf diese öffentliche Basis-URL ein.",
    "tools.setup.google.byo1": "Erstelle ein Google-Cloud-Projekt und aktiviere die APIs für Gmail, Kalender, Drive und Sheets.",
    "tools.setup.google.byo5": "Oder bitte den Agenten im Chat, dir bei der Google-Cloud-Einrichtung zu helfen.",
    "tools.setup.telegram.step1": "Öffne Telegram und sende @BotFather eine Nachricht – sende /newbot und folge den Anweisungen.",
    "tools.setup.whatsapp.step2": "Klicke auf Kopplung starten und scanne den QR-Code mit WhatsApp → Verknüpfte Geräte.",
    "tools.setup.whatsapp.step4": "Lass Babo Desktop laufen, während du erwartest, dass der Agent WhatsApp-Nachrichten empfängt.",
    "tools.setup.discord.step1": "Erstelle einen Bot im Discord Developer Portal und kopiere das Bot-Token.",
    "tools.setup.slack.step2": "Aktiviere Event Subscriptions und setze die Request URL auf:",
    "projects.command.placeholder": "Sag dem Orchestrator, was er tun soll…",
    "projects.board.unblockTitle": "Entsperren erzwingen – wechsle zu „In Bearbeitung“.",
    "auth.register.lead": "Registriere dich auf deinem Babo-Server – am selben Ort, an dem du dich über die App anmeldest.",
}

GLOBAL_FIXES: list[tuple[str, str]] = [
    ("Sparen…", "Wird gespeichert…"),
    ("Weitermachen", "Weiter"),
    ("Merkmale", "Funktionen"),
    ("Vorschriften", "Regulationen"),
    ("Gebäude...", "Wird aufgebaut…"),
    ("Gebäude…", "Wird aufgebaut…"),
    ("Stornieren", "Abbrechen"),
    ("Seelenhasch", "Soul Hash"),
    ("Selbststaat", "Selbstzustand"),
    ("Veranstaltungen", "Ereignisse"),
    ("Wendet sich", "Runden"),
    ("dreht sich", "Runden"),
    ("Drehen", "Runde"),
    ("Spielautomaten", "Slots"),
    ("Steckplätze", "Slots"),
    ("Geschäftsführer", "Exekutiv"),
    ("Ladeagent...", "Agent wird geladen…"),
    ("Ladeagent…", "Agent wird geladen…"),
    ("Gabelhöhe", "Fork-Höhe"),
    ("Gabelung...", "Fork wird erstellt…"),
    ("Gabelung…", "Fork wird erstellt…"),
    ("Hash blockieren", "Block-Hash"),
    ("Eltern-Hash", "Parent-Hash"),
    ("Nur Flüssigkeit", "Nur fluid"),
    ("Testverbindung", "Verbindung testen"),
    ("Schicken", "Senden"),
    ("Zusammenbruch", "Einklappen"),
    ("Neue Filiale", "Neuer Branch"),
    ("Als Zuhause festlegen", "Als Home setzen"),
    ("Feuchtigkeitsspendendes Gedächtnisgitter...", "Gedächtnisraster wird hydriert…"),
    ("Feuchtigkeitsspendendes Gedächtnisgitter…", "Gedächtnisraster wird hydriert…"),
    ("\"memory\": \"Erinnerung\"", "\"memory\": \"Gedächtnis\""),
    ("Was ist Erinnerung?", "Was ist Gedächtnis?"),
    ("Erinnerung und Zustand", "Gedächtnis & Zustand"),
]

# Longest phrases first — formal German UI -> informal du
FORMAL_PHRASES: list[tuple[str, str]] = [
    ("Melden Sie sich an", "Melde dich an"),
    ("melden Sie sich an", "melde dich an"),
    ("Melden Sie sich", "Melde dich"),
    ("melden Sie sich", "melde dich"),
    ("Versuchen Sie es erneut", "Versuch es erneut"),
    ("Versuchen Sie es noch einmal", "Versuch es erneut"),
    ("Versuchen Sie es", "Versuch es"),
    ("Holen Sie sich", "Hol dir"),
    ("Wenden Sie sich an", "Wende dich an"),
    ("wenden Sie sich an", "wende dich an"),
    ("Installieren Sie", "Installiere"),
    ("Wählen Sie", "Wähle"),
    ("wählen Sie", "wähle"),
    ("Geben Sie", "Gib"),
    ("geben Sie", "gib"),
    ("Verwenden Sie", "Verwende"),
    ("verwenden Sie", "verwende"),
    ("Schließen Sie", "Schließe"),
    ("schließen Sie", "schließe"),
    ("Erstellen Sie", "Erstelle"),
    ("erstellen Sie", "erstelle"),
    ("Öffnen Sie", "Öffne"),
    ("öffnen Sie", "öffne"),
    ("Setzen Sie", "Setze"),
    ("setzen Sie", "setze"),
    ("Speichern Sie", "Speichere"),
    ("speichern Sie", "speichere"),
    ("Laden Sie", "Lade"),
    ("laden Sie", "lade"),
    ("Fügen Sie", "Füge"),
    ("fügen Sie", "füge"),
    ("Starten Sie", "Starte"),
    ("starten Sie", "starte"),
    ("Stellen Sie", "Stelle"),
    ("stellen Sie", "stelle"),
    ("Konfigurieren Sie", "Konfiguriere"),
    ("konfigurieren Sie", "konfiguriere"),
    ("Klicken Sie", "Klicke"),
    ("klicken Sie", "klicke"),
    ("Tippen Sie", "Tippe"),
    ("Bestätigen Sie", "Bestätige"),
    ("Ziehen Sie", "Ziehe"),
    ("Beziehen Sie", "Beziehe"),
    ("Führen Sie", "Führe"),
    ("Finden Sie", "Finde"),
    ("finden Sie", "finde"),
    ("Überprüfen Sie", "Überprüfe"),
    ("überprüfen Sie", "überprüfe"),
    ("Warten Sie", "Warte"),
    ("Abonnieren Sie", "Abonniere"),
    ("Fahren Sie", "Fahre"),
    ("Beginnen Sie", "Beginne"),
    ("Befolgen Sie", "Befolge"),
    ("Stoppen Sie", "Stoppe"),
    ("Antworten Sie", "Antworte"),
    ("Legen Sie", "Lege"),
    ("Passen Sie", "Passe"),
    ("Gehen Sie", "Gehe"),
    ("Suchen Sie", "Suche"),
    ("Registrieren Sie", "Registriere"),
    ("Kopieren Sie", "Kopiere"),
    ("Schalten Sie", "Schalte"),
    ("Lassen Sie", "Lass"),
    ("Richten Sie", "Richte"),
    ("Koppeln Sie", "Kopple"),
    ("Aktivieren Sie", "Aktiviere"),
    ("Gewähren Sie", "Gewähre"),
    ("Senden Sie", "Sende"),
    ("Folgen Sie", "Folge"),
    ("Entfernen Sie", "Entferne"),
    ("Löschen Sie", "Lösche"),
    ("Wechseln Sie", "Wechsle"),
    ("Drücken Sie", "Drücke"),
    ("Scannen Sie", "Scanne"),
    ("Füllen Sie", "Fülle"),
    ("Überwachen Sie", "Überwache"),
    ("Überspringen Sie", "Überspringe"),
    ("Fragen Sie", "Frag"),
    ("Durchsuchen Sie", "Durchsuche"),
    ("Erhalten Sie", "Erhalte"),
    ("erhalten Sie", "erhalte"),
    ("Markieren Sie", "Markiere"),
    ("beachten Sie", "beachte"),
    ("prüfen Sie", "prüfe"),
    ("erweitern Sie", "erweitere"),
    ("Gruppieren Sie", "Gruppiere"),
    ("entfernen Sie", "entferne"),
    ("Verbinden Sie", "Verbinde"),
    ("Wiederholen Sie", "Wiederhole"),
    ("aktivieren Sie", "aktiviere"),
    ("senden Sie", "sende"),
    ("folgen Sie", "folge"),
    ("scannen Sie", "scanne"),
    ("kopieren Sie", "kopiere"),
    ("Sagen Sie", "Sag"),
    ("wechseln Sie", "wechsle"),
    ("werden Sie", "wirst du"),
    ("warten Sie mal", "warte kurz"),
    ("versuchen Sie es", "versuch es"),
    ("legen Sie", "lege"),
    ("richten Sie", "richte"),
    ("Bitten Sie", "Bitte"),
    ("Sie können", "Du kannst"),
    ("Sie sind", "Du bist"),
    ("Sie haben", "Du hast"),
    ("Sie müssen", "Du musst"),
    ("Sie werden", "Du wirst"),
    ("Sie schreiben", "du schreibst"),
    ("Sie konfigurieren", "du konfigurierst"),
    ("Sie beobachten", "Du beobachtest"),
    ("bevor Sie", "bevor du"),
    ("wenn Sie", "wenn du"),
    ("damit Sie", "damit du"),
    ("für Ihren", "für deinen"),
    ("für Ihre", "für deine"),
    ("für Ihr", "für dein"),
    ("über Ihren", "über deinen"),
    ("über Ihre", "über deine"),
    ("in Ihrem", "in deinem"),
    ("in Ihrer", "in deiner"),
    ("in Ihren", "in deinen"),
    ("an Ihren", "an deinen"),
    ("auf Ihrem", "auf deinem"),
    ("auf Ihren", "auf deinen"),
    ("von Ihrem", "von deinem"),
    ("von Ihrer", "von deiner"),
    ("Ihrem", "deinem"),
    ("Ihren", "deinen"),
    ("Ihrer", "deiner"),
    ("Ihres", "deines"),
    ("Ihre", "deine"),
    ("Ihr", "dein"),
    ("Ihnen", "dir"),
]


def flatten(d: dict, prefix: str = "") -> dict[str, str]:
    out: dict[str, str] = {}
    for k, v in d.items():
        key = f"{prefix}.{k}" if prefix else k
        if isinstance(v, dict):
            out.update(flatten(v, key))
        else:
            out[key] = str(v)
    return out


def unflatten(flat: dict[str, str]) -> dict:
    root: dict = {}
    for path, value in flat.items():
        parts = path.split(".")
        node = root
        for part in parts[:-1]:
            node = node.setdefault(part, {})
        node[parts[-1]] = value
    return root


def apply_formal_phrases(text: str) -> str:
    for old, new in FORMAL_PHRASES:
        text = text.replace(old, new)
    return text


def apply_global_fixes(text: str) -> str:
    for old, new in GLOBAL_FIXES:
        text = text.replace(old, new)
    return text


def main() -> None:
    de = json.loads(DE_PATH.read_text(encoding="utf-8"))
    flat = flatten(de)
    changed = 0

    for key, value in flat.items():
        original = value
        if key in KEY_OVERRIDES:
            value = KEY_OVERRIDES[key]
        else:
            value = apply_global_fixes(value)
            value = apply_formal_phrases(value)
        if value != original:
            flat[key] = value
            changed += 1

    DE_PATH.write_text(
        json.dumps(unflatten(flat), ensure_ascii=False, indent=2) + "\n",
        encoding="utf-8",
    )
    print(f"changed {changed} strings")


if __name__ == "__main__":
    main()
